---

- name: "run baseline"
  import_playbook: baseline.yaml

- name: "update the node with the latest configuration"
  hosts: all
  vars:
    host_files: "{{ playbook_dir }}/files/{{ inventory_hostname }}"
  gather_facts: true

  tasks:
    - name: "import xorg"
      import_role:
        name: xorg
      vars:
        xorg_conf_d_files: >-
          "{{ host_files }}/etc/X11/xorg.conf.d/"
      tags: xorg
  

    - name: "import host roles"
      include_role:
        name: "{{ role }}"
        apply:
          tags: "{{ role }}"
      tags: always
      loop: "{{ extra_roles }}"
      loop_control:
        loop_var: "role"
