---

- name: "setup client with current configuration"
  hosts: all
  gather_facts: true
  tasks:
    - name: "setup linux_system"
      import_role:
        name: linux_system
      tags: system

    - name: "setup xorg"
      import_role:
        name: xorg
      vars:
        xorg_conf_d_files: >-
          "{{ host_files }}/etc/X11/xorg.conf.d/"
      tags: xorg
    
    - name: "create users"
      import_role:
        name: users
      tags: users
  
    - name: "include host roles"
      include_role:
        name: "{{ role }}"
        apply:
          tags: "{{ role }}"
      tags: always
      loop: "{{ extra_roles }}"
      loop_control:
        loop_var: "role"

