- name: install xorg x11 window system
  become: true
  community.general.pacman: 
    name: 
    - xorg-server
    - xorg-xinit
    - xorg-xrandr
    - xorg-xdm
    - xorg-xlsfonts
    state: latest
  notify: 'reconfigure x11'

- name: install system x11 configuration
  become: true
  ansible.builtin.template:
    src: "X11/{{ item.0 }}"
    dest: "/etc/X11/{{ item.1 }}"
  loop:
  - [xinitrc.j2,    xinit/xinitrc]
  - [Xresources.j2, xdm/Xresources]
  - [Xsession.j2,   xdm/Xsession]
  notify: 'reconfigure x11'


    # TODO: This source should be outside the role
- name: copy host specific xorg.conf.d
  become: true
  ansible.builtin.copy:
    src: 'xorg.conf.d/'
    dest: '/etc/X11/xorg.conf.d/'
  notify: 'reconfigure x11'
