---

- name: restart sshd service
  become: true
  ansible.builtin.systemd:
    name: sshd.service
    state: restarted
  async: &asynctimeout 60
  ignore_errors: true
  poll: 0

- name: reconnect
  ansible.builtin.wait_for_connection:
    timeout: *asynctimeout
