---

sshd_config: |
  PermitRootLogin no
  AuthorizedKeysFile .ssh/authorized_keys
  PasswordAuthentication no
  ChallengeResponseAuthentication no
  UsePAM yes
  PrintMotd no
  X11Forwarding yes
  Subsystem	sftp /usr/lib/ssh/sftp-server
  ClientAliveInterval 60
  ClientAliveCountMax 5
